-- init-database.sql
CREATE TABLE IF NOT EXISTS users (
  id INT UNSIGNED PRIMARY KEY AUTO_INCREMENT,
  username VARCHAR(255) NOT NULL UNIQUE,
  password_hash VARCHAR(255) NOT NULL,
  role ENUM('admin','user') NOT NULL DEFAULT 'admin',
  created_at DATETIME DEFAULT CURRENT_TIMESTAMP,
  updated_at DATETIME DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP
);

CREATE TABLE IF NOT EXISTS mis_students (
  id INT UNSIGNED PRIMARY KEY AUTO_INCREMENT,
  name VARCHAR(255) NOT NULL,
  class VARCHAR(100) NOT NULL,
  academic_year VARCHAR(50) NOT NULL,
  student_id VARCHAR(255) NOT NULL UNIQUE,
  school_code VARCHAR(100) NOT NULL,
  created_at DATETIME DEFAULT CURRENT_TIMESTAMP,
  updated_at DATETIME DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP
);

CREATE TABLE IF NOT EXISTS mis_teachers (
  id INT UNSIGNED PRIMARY KEY AUTO_INCREMENT,
  name VARCHAR(255) NOT NULL,
  teacher_id VARCHAR(255) NOT NULL UNIQUE,
  academic_year VARCHAR(50) NOT NULL,
  school_code VARCHAR(100) NOT NULL,
  designation VARCHAR(255) NOT NULL,
  created_at DATETIME DEFAULT CURRENT_TIMESTAMP,
  updated_at DATETIME DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP
);

CREATE TABLE IF NOT EXISTS approval_requests (
  id INT UNSIGNED PRIMARY KEY AUTO_INCREMENT,
  name VARCHAR(255) NOT NULL,
  entity_type ENUM('student','teacher') NOT NULL,
  data_fields JSON NOT NULL,
  status ENUM('Pending','Approved','Rejected') NOT NULL DEFAULT 'Pending',
  remarks TEXT,
  requested_by INT UNSIGNED,
  created_at DATETIME DEFAULT CURRENT_TIMESTAMP,
  updated_at DATETIME DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP
);

CREATE TABLE IF NOT EXISTS audit_trail (
  id INT UNSIGNED PRIMARY KEY AUTO_INCREMENT,
  action ENUM('upload','approve','reject','edit') NOT NULL,
  entity_type ENUM('student','teacher','approval_request') NOT NULL,
  entity_id INT UNSIGNED,
  user_id INT UNSIGNED,
  remarks TEXT,
  timestamp DATETIME DEFAULT CURRENT_TIMESTAMP
);
